# Exercise3
## Logistic Regression

In [2]:
# 필요한 라이브러리를 임포트합니다.

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize # optimization

#import utils
#grader = utils.Grader()

np.random.seed(42) # reproduction을 위한 random seed 고정

# tells matplotlib to embed plots within the notebook
%matplotlib inline 

## 1. Logistic Regression
logistic regression을 활용하여 분류 모델을 생성합니다.

In [ ]:
# 데이터 불러오기
# X : column 0, 1
# y : column 2
data = np.loadtxt(os.path.join('Data', 'ex2data1.txt'), delimiter=',')
X, y = data[:, 0:2], data[:, 2]

In [ ]:
# 데이터 확인
data[:10]

In [ ]:
# X, y 확인
X[:10], y[:10]

### 1.1 Visualize the data
본격적으로 분류를 하기 전에 데이터를 시각화 해보겠습니다. plotData 함수로 2차원 플롯을 그려보겠습니다. X1, X2를 각각의 축으로 삼고 라벨에 따라 다른 마커로 데이터를 표시해주세요. 아래의 코드를 참고하여 plotData 함수를 작성해주세요.

```python
# Find Indices of Positive and Negative Examples
pos = y == 1
neg = y == 0

# Plot Examples
plt.plot(X[pos, 0], X[pos, 1], 'k*', lw=2, ms=10)
plt.plot(X[neg, 0], X[neg, 1], 'ko', mfc='y', ms=8, mec='k', mew=1)
```

In [ ]:
def plotData(X, y):
    
    fig = pyplot.figure()

    # ====================== YOUR CODE HERE ======================

    
    # ============================================================
    
    plt.xlabel('X1')
    plt.ylabel('X2')
    plt.legend(['positive', 'negative'])

In [ ]:
plotData(X, y)

### 1.2 구현 

#### 1.2.1 Sigmoid function

> sigmoid function의 정의 : $ g(z) = \frac{1}{1+e^{-z}} $.

첫번째 과제는 sigmoid function을 구현하는 것입니다. 

X가 커질수록 1에 가까운 값이 나오고, 작아질수록 0에 가까운 값이 나오고, 0일 경우 0.5의 값이 나와야합니다. 

벡터와 행렬 입력에서 작동해야 합니다.



In [ ]:
# 지정한 array y에 대해 exponential 을 적용해보세요
np.exp(y)

In [ ]:
def sigmoid(z):
    
    # 입력 z를 array로 변환
    z = np.array(z)
    

    # ====================== YOUR CODE HERE ======================
    # 변수 g에 할당해주세요.
    
    g = None

    # =============================================================
    return g

In [ ]:
# Test
# 0을 넣을 경우 0.5를 출력해야 합니다.
z = 0
g = sigmoid(z)

print('g(', z, ') = ', g)

In [ ]:
grader.answer[0] = sigmoid
grader.grade(0)

### 1.2.2 Cost function and Gradient
logistic regression의 cost function과 gradient를 구현해보겠습니다.

In [ ]:
# X에 상수항 추가 (한번만 해주세요)
m, n = X.shape
X = np.concatenate([np.ones((m, 1)), X], axis=1)

> logistic regression의 hypothesis : $ h_\theta(x) = g(\theta^T x)$

> cost function : $ J(\theta) = \frac{1}{m} \sum_{i=1}^{m} \left[ -y^{(i)} \log\left(h_\theta\left( x^{(i)} \right) \right) - \left( 1 - y^{(i)}\right) \log \left( 1 - h_\theta\left( x^{(i)} \right) \right) \right] $

> gradient of $\theta_j$ : $ \frac{\partial J(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^m \left( h_\theta \left( x^{(i)} \right) - y^{(i)} \right) x_j^{(i)} $

gradient의 정의가 linear regression과 동일해보이지만, hypothesis가 다르기 때문에 차이가 있습니다.

In [ ]:
# theta가 [A, B, C] 형태로 주어졌을때 각 data point에 대해 hypothesis 를 구해보세요
# A*X0 + B*X1 + C*X2 에 앞서 정의한 sigmoid 함수가 적용된 후 각 data point에 대한 hypothesis 값이 나와야합니다.
# 따라서 (m,)의 shape을 가진 array로 출력이 되어야 합니다.

theta = [0.01, 0.01, 0.01] # 예제 theta
hypothesis = None

print(hypothesis)

In [ ]:
# 앞서 구한 hypothesis 값을 이용해 Cost를 출력해 보세요
# 각 data point들에 대해 각각 계산이 되어 (m,) 형태의 array로 출력이 되어야 합니다.
J_array = None
print(J_array)

In [ ]:
# 이제 앞에서 구한 각 data point들의 값을 다 더하고 총 데이터의 개수로 나누어 주어 이를 J에 할당하겠습니다.
# 총 데이터의 개수는 m 입니다.
m = J_array.size
J = np.sum(J_array) / m
print(J)

In [ ]:
# theta에 대한 gradient를 구해 보겠습니다
# 에시로 theta[0]에 대해 gradient를 구해 보겠습니다.
# 첫번째로 앞서 구한 hypothesis 값을 y로 뺀 다음 X의 0번째 열을 곱해주겠습니다. 즉 (hypothesis - y)*X[0] 가 되어야 합니다.

grad_theta0_array = None
print(grad_theta0_array)

In [ ]:
# 이제 이 각 data point의 gradient 값의 평균을 구합니다.
grad_theta0 = None
print(grad_zero)

In [ ]:
# 위와 같은 과정을 일반화해서 함수로 나타내 주세요! Main 문제 입니다.
# gradient를 구할때 for 문을 이용해 여러개의 theta에 대해 반복적으로 진행하게 나타낼 수 있습니다.

def costFunction(theta, X, y):

    # Initialize some useful values
    m = y.size  # train data의 수
    grad = np.ones_like(theta) # grad 틀


    # ====================== YOUR CODE HERE ======================
    
    J = None
    grad = None
    
    
    # =============================================================
    return J, grad

In [ ]:
# Initialize fitting parameters
initial_theta = np.zeros(n+1)

cost, grad = costFunction(initial_theta, X, y)

print('Cost at initial theta (zeros): {:.3f}'.format(cost))
print('Expected cost (approx): 0.693\n')

print('Gradient at initial theta (zeros):')
print('\t[{:.4f}, {:.4f}, {:.4f}]'.format(*grad))
print('Expected gradients (approx):\n\t[-0.1000, -12.0092, -11.2628]\n')

# Compute and display cost and gradient with non-zero theta
test_theta = np.array([-24, 0.2, 0.2])
cost, grad = costFunction(test_theta, X, y)

print('Cost at test theta: {:.3f}'.format(cost))
print('Expected cost (approx): 0.218\n')

print('Gradient at test theta:')
print('\t[{:.3f}, {:.3f}, {:.3f}]'.format(*grad))
print('Expected gradients (approx):\n\t[0.043, 2.566, 2.647]')

In [ ]:
grader.answer(1) = costFunction
grader.grade(1)

In [ ]:
grader.answer(2) = costFunction
grader.grade(2)

### 1.2.3 `scipy.optimize`로 학습하기

지금까지 gradient descent alorithm을 직접 구현해 최적화를 했습니다. 오늘은 `scipy.optimize` 함수를 통해 최적화를 실시하겠습니다.
`optimize.minimize`를 통해 cost function $J(\theta)$ 를 최소화하는 parameter $\theta$ 찾아보겠습니다.

`optimize.minimize`는 다음과 같은 파라미터를 필요로 합니다.
* `costFunction` : 최적화시킬 비용함수
* `initial_theta` : 파라미터의 초기값
* `(X, y)` : 데이터
* `jac` : gradient vector 출력여부 (True)
* `method` : 최적화 알고리즘
* `options` : 기타 튜닝 옵션

`optimize.minize`를 쓸 때 loop를 쓰거나, learning rate를 지정할 필요가 없습니다. 최적화가 진행된 후 cost와 $\theta$를 출력하게 됩니다. 

In [ ]:
# set options for optimize.minimize
options= {'maxiter': 400}

# The function returns an object `OptimizeResult`
result = optimize.minimize(costFunction,
                        initial_theta,
                        (X, y),
                        jac=True,
                        method='TNC',
                        options=options)

# the fun property of `OptimizeResult` object returns
cost = result.fun # 최종 cost
theta = result.x # 최종 theta

# Print theta to screen
print('Cost at theta found by optimize.minimize: {:.3f}'.format(cost))
print('Expected cost (approx): 0.203\n');

print('theta:')
print('\t[{:.3f}, {:.3f}, {:.3f}]'.format(*theta))
print('Expected theta (approx):\n\t[-25.161, 0.206, 0.201]')

### 1.2.4 Evaluating logistic regression
최적화된 모델의 성능을 확인해봅시다.


In [ ]:
# 가장 먼저 앞에서 optimize로 구한 최적의 theta값을 이용해 hypothesis 를 구해보겠습니다.
# sigmoid function을 이용해 (m,) shape의 array가 나오면 됩니다.
hypothesis = None

In [ ]:
# 이제 이 hypothesis를 0과 1로 분류해야합니다.
# 각 data point의 값이 0.5보다 작으면 0, 0.5보다 크면 1입니다.
# list comprehension or map 함수를 사용해보세요
predict = None

In [ ]:
def predict(theta, X):
stic regression parameters.You should set p to a vector of 0's and 1's    

    # ====================== YOUR CODE HERE ======================
    p = None
    # ============================================================
    return p

In [ ]:
# Predict 예제
prob = sigmoid(np.dot([1, 45, 85], theta))
print('For a student with scores 45 and 85,'
      'we predict an admission probability of {:.3f}'.format(prob))
print('Expected value: 0.775 +/- 0.002\n')

# Compute accuracy on our training set
p = predict(theta, X)
print('Train Accuracy: {:.2f} %'.format(np.mean(p == y) * 100))
print('Expected accuracy (approx): 89.00 %')

In [ ]:
grader.answer[4] = predict
grader.grade()

## 2. Regularized Logistic Regression
regularized logistic regression을 구현해보도록 하겠습니다.먼저 데이터를 불러오겠습니다.

In [3]:
# 데이터 불러오기
# X : column 0, 1
# y : column 2
data = np.loadtxt(os.path.join('Data', 'ex2data2.txt'), delimiter=',')
X = data[:, :2]
y = data[:, 2]

In [4]:
data[:10]

array([[ 0.051267,  0.69956 ,  1.      ],
       [-0.092742,  0.68494 ,  1.      ],
       [-0.21371 ,  0.69225 ,  1.      ],
       [-0.375   ,  0.50219 ,  1.      ],
       [-0.51325 ,  0.46564 ,  1.      ],
       [-0.52477 ,  0.2098  ,  1.      ],
       [-0.39804 ,  0.034357,  1.      ],
       [-0.30588 , -0.19225 ,  1.      ],
       [ 0.016705, -0.40424 ,  1.      ],
       [ 0.13191 , -0.51389 ,  1.      ]])

In [5]:
X[:10], y[:10]

(array([[ 0.051267,  0.69956 ],
        [-0.092742,  0.68494 ],
        [-0.21371 ,  0.69225 ],
        [-0.375   ,  0.50219 ],
        [-0.51325 ,  0.46564 ],
        [-0.52477 ,  0.2098  ],
        [-0.39804 ,  0.034357],
        [-0.30588 , -0.19225 ],
        [ 0.016705, -0.40424 ],
        [ 0.13191 , -0.51389 ]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
poly = PolynomialFeatures(6)

In [8]:
poly.fit_transform(X)

array([[ 1.00000000e+00,  5.12670000e-02,  6.99560000e-01, ...,
         6.29470940e-04,  8.58939846e-03,  1.17205992e-01],
       [ 1.00000000e+00, -9.27420000e-02,  6.84940000e-01, ...,
         1.89305413e-03, -1.39810280e-02,  1.03255971e-01],
       [ 1.00000000e+00, -2.13710000e-01,  6.92250000e-01, ...,
         1.04882142e-02, -3.39734512e-02,  1.10046893e-01],
       ...,
       [ 1.00000000e+00, -4.84450000e-01,  9.99270000e-01, ...,
         2.34007252e-01, -4.82684337e-01,  9.95627986e-01],
       [ 1.00000000e+00, -6.33640000e-03,  9.99270000e-01, ...,
         4.00328554e-05, -6.31330588e-03,  9.95627986e-01],
       [ 1.00000000e+00,  6.32650000e-01, -3.06120000e-02, ...,
         3.51474517e-07, -1.70067777e-08,  8.22905998e-10]])

The above figure shows that our dataset cannot be separated into positive and negative examples by a straight-line through the plot. Therefore, a straight-forward application of logistic regression will not perform well on this dataset since logistic regression will only be able to find a linear decision boundary.

### 2.2 Feature mapping

One way to fit the data better is to create more features from each data point. In the function `mapFeature` defined in the file `utils.py`, we will map the features into all polynomial terms of $x_1$ and $x_2$ up to the sixth power.

$$ \text{mapFeature}(x) = \begin{bmatrix} 1 & x_1 & x_2 & x_1^2 & x_1 x_2 & x_2^2 & x_1^3 & \dots & x_1 x_2^5 & x_2^6 \end{bmatrix}^T $$

As a result of this mapping, our vector of two features (the scores on two QA tests) has been transformed into a 28-dimensional vector. A logistic regression classifier trained on this higher-dimension feature vector will have a more complex decision boundary and will appear nonlinear when drawn in our 2-dimensional plot.
While the feature mapping allows us to build a more expressive classifier, it also more susceptible to overfitting. In the next parts of the exercise, you will implement regularized logistic regression to fit the data and also see for yourself how regularization can help combat the overfitting problem.
