In [1]:
import numpy as np

In [11]:
m = np.array([1,2,3])
n = np.array([[1,2,4],
              [2,3,5],
              [1,1,1]])
np.matmul(n, m)

array([17, 23,  6])

#### np.array() : array의 형태를 만들어줍니다

#### 리스트, 데이터프레임 등의 데이터를 넣어서 array로 만들어 주거나 직접 써서 array형태를 만들 수 있습니다

#### 파이썬 리스트와 마찬가지로 [:, :] 방식으로 인덱싱을 할 수 있습니다

In [12]:
A = np.array([[1, 2, 3],
          [4, 5, 6]])
B = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[-1, -2, -3],
               [-4, -5, -6]]])
C = np.array([1, 2, 3])
D = np.array([[1, 2, 3]])

In [13]:
A[0, :]

array([1, 2, 3])

#### np.shape : array의 형태를 보여줍니다

#### np.size : array의 각 값의 개수를 나타내 줍니당

#### np.ndim : array의 dimension을 확인할 수 있습니다

In [31]:
A.shape, B.shape, C.shape, D.shape

((2, 3), (2, 2, 3), (3,), (1, 3))

In [32]:
A.size, B.size, C.size

(6, 12, 3)

In [33]:
A.ndim, B.ndim, C.ndim, D.ndim

(2, 3, 1, 2)

#### np.zeros() : 0을 지정해준 shape만큼 array 형태로 만들어 줍니다

#### np.ones() : 1을 지정해준 shape만큼 array 형태로 만들어 줍니다

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

#### np. concatenate() : 여러개의 array를 이어 붙일 수 있습니다

In [16]:
A = np.array([[1, 1],
              [2, 2]])
B = np.array([[1, 1],
              [2, 2],
              [3, 3]])
C = np.array([[4, 5, 6],
              [7, 8, 9]])
A.shape, B.shape, C.shape

((2, 2), (3, 2), (2, 3))

In [17]:
new = np.concatenate((A, B), axis = 0)
new, new.shape

(array([[1, 1],
        [2, 2],
        [1, 1],
        [2, 2],
        [3, 3]]), (5, 2))

In [104]:
new2 = np.concatenate((A, C), axis = 1)
new2, new2.shape

(array([[1, 1, 4, 5, 6],
        [2, 2, 7, 8, 9]]), (2, 5))

## Quiz

### 0으로 구성된 2x2 행렬과 1로 구성된 2x3 행렬을 array형태로 변수 T, N에 저장하고  
### [1 1 1 0 0]  
### [1 1 1 0 0]  
### 의 형태로 나타내보세요!

In [19]:
T = np.zeros((2,2))
N = np.ones((2,3))
np.concatenate((N, T), axis = 1)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

### numpy 기초연산

- 같은 shape을 가지는 array끼리의 연산일 경우 각 값끼리 계산합니다.
- 다른 shape을 가지는 array끼리의 연산일 경우 **누락되었거나 길이가 1인 차원에 대해** 브로드캐스팅이 수행됩니다.

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [38]:
X = np.array([[1, -1],
              [2, -2]])
Y = np.array([[3, -3],
              [4, -4]])

In [39]:
X + Y, X * Y

(array([[ 4, -4],
        [ 6, -6]]), array([[3, 3],
        [8, 8]]))

In [57]:
X ** 2

array([[1, 1],
       [4, 4]], dtype=int32)

In [42]:
A, A.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [43]:
C, C.shape

(array([1, 2, 3]), (3,))

In [47]:
A + C

array([[2, 4, 6],
       [5, 7, 9]])

## Quiz  
### (T + 2) ** 2 + N 을 했을 때 어떤 결과값이 나올지 생각해 보고 한번 실행시켜 보세요!

In [108]:
T = np.array([[1, 2, -1]])
N = np.array([[-2],
              [1],
              [-2]])
T.shape, N.shape

((1, 3), (3, 1))

### numpy의 행렬연산

- 행렬 곱셈  
    np.dot()
    np.matmul()
      
- 행렬의 transpose  
    array.T
      
- 행렬 각 요소의 제곱 값  
    np.square()
    
- 역행렬 계산  
    np.linalg.pinv

In [65]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[3, 4],
              [1, 2]])
np.dot(a, b)

array([[ 5,  8],
       [13, 20]])

In [66]:
np.matmul(a, b)

array([[ 5,  8],
       [13, 20]])

In [67]:
a.T

array([[1, 3],
       [2, 4]])

In [68]:
np.square(a)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [85]:
np.linalg.pinv(a)

array([[-0.2,  0.4],
       [ 0.3, -0.1]])

## Quiz

### 1. T x N 연산을 하고
### 2. 계산 된 행렬의 좌측 위 2x2 행렬을 추출해 transpose를 구하고
### 3. 그 행렬의 inverse를 구해봅시다!
### array([[ 1.27777778, -1.55555556],
###       [-0.44444444,  0.55555556]]) 가 출력되면 정답!

In [110]:
T = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
N = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

### Numpy의 기초 통계 연산

-  np.mean(), np.sum() : 평균 값, 합 값 계산

- np.std(), np.var() : 표준편차, 분산 값 계산

- np.min(), np.max() : 최소, 최대값 계산

- np.argmax(), np.argmin() : 최대, 최소값의 index 계산  



In [20]:
b = np.array([[1, 4],
              [3, 2]])

In [21]:
b.mean(), b.min(), b.std() # 전체 요소의 평균, 최소값, 표준편차를 구함

(2.5, 1, 1.118033988749895)

In [22]:
b.mean(axis = 0) # 행끼리 계산!! -> 각 컬럼의 평균 값을 구할 수 있다.

array([2., 3.])

In [23]:
b.std(axis = 1) # 열끼리 계산!! -> 각 row의 표준편차 값을 구할 수 있다.

array([1.5, 0.5])

In [84]:
b.argmax(axis = 0) # 행끼리 봤을때 큰 쪽의 index값 반환! -> 각 컬럼에서의 가장 큰 값을 가지는 index를 반환

array([1, 0], dtype=int64)

## Quiz
### 주어진 T의 값을 이용해
[2 3 4]  
[3 4 5]  
[4 5 6] 
### 1. 행렬을 만들고 (Hint : transpose 연산을 잘 활용해 보세용)
### 2. 그 행렬의 inverse를 구한 뒤
### 3. 각 컬럼의 평균과 표준편차를 구해보세요!
### 평균 : [-1.66666667e-01, -2.40548322e-16,  1.66666667e-01]
### 표준편차 : [0.95257934, 0.13608276, 0.68041382] 가 나오면 정답!

In [34]:
T = np.array([[1, 2, 3]])

In [35]:
T.T

array([[1],
       [2],
       [3]])

In [37]:
N = np.linalg.pinv(T + T.T)
N

array([[-1.33333333e+00, -1.66666667e-01,  1.00000000e+00],
       [-1.66666667e-01, -4.19263070e-17,  1.66666667e-01],
       [ 1.00000000e+00,  1.66666667e-01, -6.66666667e-01]])

In [38]:
N.mean(axis = 0), N.std(axis = 0)

(array([-1.66666667e-01, -2.40548322e-16,  1.66666667e-01]),
 array([0.95257934, 0.13608276, 0.68041382]))

In [2]:
import numpy as np

#### np.array() : array의 형태를 만들어줍니다

#### 리스트, 데이터프레임 등의 데이터를 넣어서 array로 만들어 주거나 직접 써서 array형태를 만들 수 있습니다

#### 파이썬 리스트와 마찬가지로 [:, :] 방식으로 인덱싱을 할 수 있습니다

In [30]:
A = np.array([[1, 2, 3],
          [4, 5, 6]])
B = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[-1, -2, -3],
               [-4, -5, -6]]])
C = np.array([1, 2, 3])
D = np.array([[1, 2, 3]])

In [59]:
A[0, :]

array([1, 2, 3])

#### np.shape : array의 형태를 보여줍니다

#### np.size : array의 각 값의 개수를 나타내 줍니당

#### np.ndim : array의 dimension을 확인할 수 있습니다

In [31]:
A.shape, B.shape, C.shape, D.shape

((2, 3), (2, 2, 3), (3,), (1, 3))

In [32]:
A.size, B.size, C.size

(6, 12, 3)

In [33]:
A.ndim, B.ndim, C.ndim, D.ndim

(2, 3, 1, 2)

#### np.zeros() : 0을 지정해준 shape만큼 array 형태로 만들어 줍니다

#### np.ones() : 1을 지정해준 shape만큼 array 형태로 만들어 줍니다

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

#### np. concatenate() : 여러개의 array를 이어 붙일 수 있습니다

In [103]:
A = np.array([[1, 1],
              [2, 2]])
B = np.array([[1, 1],
              [2, 2],
              [3, 3]])
C = np.array([[4, 5, 6],
              [7, 8, 9]])
A.shape, B.shape, C.shape

((2, 2), (3, 2), (2, 3))

In [97]:
new = np.concatenate((A, B), axis = 0)
new, new.shape

(array([[1, 1],
        [2, 2],
        [1, 1],
        [2, 2],
        [3, 3]]), (5, 2))

In [104]:
new2 = np.concatenate((A, C), axis = 1)
new2, new2.shape

(array([[1, 1, 4, 5, 6],
        [2, 2, 7, 8, 9]]), (2, 5))

## Quiz

### 0으로 구성된 2x2 행렬과 1로 구성된 2x3 행렬을 array형태로 변수 T, N에 저장하고  
### [1 1 1 0 0]  
### [1 1 1 0 0]  
### 의 형태로 나타내보세요!

### numpy 기초연산

- 같은 shape을 가지는 array끼리의 연산일 경우 각 값끼리 계산합니다.
- 다른 shape을 가지는 array끼리의 연산일 경우 **누락되었거나 길이가 1인 차원에 대해** 브로드캐스팅이 수행됩니다.

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [38]:
X = np.array([[1, -1],
              [2, -2]])
Y = np.array([[3, -3],
              [4, -4]])

In [39]:
X + Y, X * Y

(array([[ 4, -4],
        [ 6, -6]]), array([[3, 3],
        [8, 8]]))

In [57]:
X ** 2

array([[1, 1],
       [4, 4]], dtype=int32)

In [42]:
A, A.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [43]:
C, C.shape

(array([1, 2, 3]), (3,))

In [47]:
A + C

array([[2, 4, 6],
       [5, 7, 9]])

## Quiz  
### (T + 2) ** 2 + N 을 했을 때 어떤 결과값이 나올지 생각해 보고 한번 실행시켜 보세요!

In [108]:
T = np.array([[1, 2, -1]])
N = np.array([[-2],
              [1],
              [-2]])
T.shape, N.shape

((1, 3), (3, 1))

### numpy의 행렬연산

- 행렬 곱셈  
    np.dot()
    np.matmul()
      
- 행렬의 transpose  
    array.T
      
- 행렬 각 요소의 제곱 값  
    np.square()
    
- 역행렬 계산  
    np.linalg.pinv

In [65]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[3, 4],
              [1, 2]])
np.dot(a, b)

array([[ 5,  8],
       [13, 20]])

In [66]:
np.matmul(a, b)

array([[ 5,  8],
       [13, 20]])

In [67]:
a.T

array([[1, 3],
       [2, 4]])

In [68]:
np.square(a)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [85]:
np.linalg.pinv(a)

array([[-0.2,  0.4],
       [ 0.3, -0.1]])

## Quiz

### 1. T x N 연산을 하고
### 2. 계산 된 행렬의 좌측 위 2x2 행렬을 추출해 transpose를 구하고
### 3. 그 행렬의 inverse를 구해봅시다!
### array([[ 1.27777778, -1.55555556],
###       [-0.44444444,  0.55555556]]) 가 출력되면 정답!

In [31]:
T = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
N = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [33]:
np.linalg.pinv(np.matmul(T, N)[0:2, 0:2].T)

array([[ 1.27777778, -1.55555556],
       [-0.44444444,  0.55555556]])

### Numpy의 기초 통계 연산

-  np.mean(), np.sum() : 평균 값, 합 값 계산

- np.std(), np.var() : 표준편차, 분산 값 계산

- np.min(), np.max() : 최소, 최대값 계산

- np.argmax(), np.argmin() : 최대, 최소값의 index 계산  



In [80]:
b = np.array([[1, 4],
              [3, 2]])

In [81]:
b.mean(), b.min(), b.std() # 전체 요소의 평균, 최소값, 표준편차를 구함

(2.5, 1, 1.118033988749895)

In [82]:
b.mean(axis = 0) # 행끼리 계산!! -> 각 컬럼의 평균 값을 구할 수 있다.

array([2., 3.])

In [83]:
b.std(axis = 1) # 열끼리 계산!! -> 각 row의 표준편차 값을 구할 수 있다.

array([2.5, 2.5])

In [84]:
b.argmax(axis = 0) # 행끼리 봤을때 큰 쪽의 index값 반환! -> 각 컬럼에서의 가장 큰 값을 가지는 index를 반환

array([1, 0], dtype=int64)

## Quiz
### 주어진 T의 값을 이용해
[2 3 4]  
[3 4 5]  
[4 5 6] 
### 1. 행렬을 만들고 (Hint : transpose 연산을 잘 활용해 보세용)
### 2. 그 행렬의 inverse를 구한 뒤
### 3. 각 컬럼의 평균과 표준편차를 구해보세요!
### 평균 : [-1.66666667e-01, -2.40548322e-16,  1.66666667e-01]
### 표준편차 : [0.95257934, 0.13608276, 0.68041382] 가 나오면 정답!

In [123]:
T = np.array([[1, 2, 3]])